/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/cami/Documents/GitHub/st0263/Reto1/tracker.py': [Errno 2] No such file or directory
